# Generated by Django 2.0.2 on 2018-09-14 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='char',
            new_name='Char',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='image',
            new_name='Image',
        ),
    ]
